# Generated by Django 2.1.1 on 2018-09-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='gsa_10',
        ),
    ]
