# Generated by Django 2.1.1 on 2018-09-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_vendor_gsa_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gsa_10',
            field=models.TextField(blank=True, null=True),
        ),
    ]
